name: 28539 Test

on:
  push:
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/28539_test.yml'
  pull_request:

jobs:
  preveri-teste:
    runs-on: ubuntu-latest
    outputs:
      napaka_obstaja: ${{ steps.preveri.outputs.napaka_obstaja }}

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Preveri ali obstajajo testi
        id: preveri
        run: |
          if ls tests/test_*.py > /dev/null 2>&1; then
            echo "Testne skripte obstajajo." > napaka.txt
            echo "napaka_obstaja=false" >> $GITHUB_OUTPUT
          else
            echo "Napaka: Ni testnih skript!" > napaka.txt
            echo "napaka_obstaja=true" >> $GITHUB_OUTPUT
          fi

      - name: Shrani napaka.txt kot artefakt
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  izvedi-teste:
    needs: preveri-teste
    if: needs.preveri-teste.outputs.napaka_obstaja == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12, 3.11]

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Prenesi napaka.txt
        uses: actions/download-artifact@v4
        with:
          name: napaka
          path: ./artefakti

      - name: Prikaži napaka.txt
        run: cat ./artefakti/napaka.txt

      - name: Namesti odvisnosti za Python ${{ matrix.python-version }}
        run: |
          sudo apt update
          sudo apt install -y python3-opencv python3-pip
          python${{ matrix.python-version }} -m pip install --upgrade pip
          python${{ matrix.python-version }} -m pip install -r requirements.txt

      - name: Zaženi teste za Python ${{ matrix.python-version }}
        run: |
          python${{ matrix.python-version }} -m unittest discover -s tests
