name: 28539 Deploy

on:
  workflow_run:
    workflows: ["28539 Test"]  # Ime prve skripte
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v4

      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Zgradi Docker sliko
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/moj-projekt:latest .

      - name: Potisni sliko na DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/moj-projekt:latest
